# -*- coding: utf-8 -*-
"""
Created on Thu Apr 29 19:51:43 2021

@author: Houcemeddine Turki
"""
countries = {"Afghanistan": "afg",
"United Arab Emirates": "are",
"Argentina": "arg",
"Armenia": "arm",
"Australia": "aus",
"Austria": "aut",
"Azerbaijan": "aze",
"Burundi": "bdi",
"Belgium": "bel",
"Benin": "ben",
"Burkina Faso": "bfa",
"Bangladesh": "bgd",
"Bulgaria": "bgr",
"Bahrain": "bhr",
"Bahamas": "bhs",
"Bosnia and Herzegovina": "bih",
"Belarus": "blr",
"Bermuda": "bmu",
"Brazil": "bra",
"Brunei Darussalam": "brn",
"Botswana": "bwa",
"Canada": "can",
"Switzerland": "che",
"Chile": "chl",
"China": "chn",
"Cameroon": "cmr",
"Congo": "cog",
"Colombia": "col",
"Costa Rica": "cri",
"Cuba": "cub",
"Curaçao": "cuw",
"Cyprus": "cyp",
"Czech Republic": "cze",
"Czech": "cze",
"Germany": "deu",
"Dominica": "dma",
"Denmark": "dnk",
"Algeria": "dza",
"Ecuador": "ecu",
"Egypt": "egy",
"Eritrea": "eri",
"Spain": "esp",
"Estonia": "est",
"Ethiopia": "eth",
"Finland": "fin",
"Fiji": "fji",
"Falkland Islands": "flk",
"France": "fra",
"Gabon": "gab",
"United Kingdom": "gbr",
"Georgia": "geo",
"Ghana": "gha",
"Gambia": "gmb",
"Guinea Bissau": "gnb",
"Greece": "grc",
"Grenada": "grd",
"Greenland": "grl",
"Guatemala": "gtm",
"French Guiana": "guf",
"Haiti": "hai",
"Hong Kong": "hkg",
"China-Hong Kong": "hkg",
"Croatia": "hrv",
"Hungary": "hun",
"Indonesia": "idn",
"India": "ind",
"Ireland": "irl",
"Iran": "irn",
"Iraq": "irq",
"Iceland": "isl",
"Israel": "isr",
"Italy": "ita",
"Jamaica": "jam",
"Jordan": "jor",
"Japan": "jpn",
"Kazakhstan": "kaz",
"Kenya": "ken",
"Cambodia": "khm",
"Saint Kitts and Nevis": "kna",
"South Korea": "kor",
"Kuwait": "kwt",
"Laos": "lao",
"Lebanon": "lbn",
"Libya": "lby",
"Saint Lucia": "lca",
"Liechtenstein": "lie",
"Sri Lanka": "lka",
"Lesotho": "lso",
"Lithuania": "ltu",
"Luxembourg": "lux",
"Latvia": "lva",
"Macao": "mac",
"China-Macau": "mac",
"Morocco": "mar",
"Monaco": "mco",
"Moldova": "mda",
"Madagascar": "mdg",
"Mexico": "mex",
"North Macedonia": "mkd",
"Mali": "mli",
"Malta": "mlt",
"Montenegro": "mne",
"Mauritius": "mus",
"Malawi": "mwi",
"Malaysia": "mys",
"Niger": "nig",
"Angola": "ang",
"Belize": "blz",
"Bhutan": "bhu",
"Guinea": "gui",
"Zambia": "zam",
"Albania": "alb",
"Bolivia": "bol",
"Liberia": "lib",
"Myanmar": "mya",
"Reunion": "reu",
"Somalia": "som",
"Anguilla": "aia",
"Barbados": "bar",
"Djibouti": "dji",
"Honduras": "hon",
"Maldives": "mld",
"Mongolia": "mon",
"Paraguay": "par",
"Suriname": "sur",
"Nicaragua": "nic",
"Swaziland": "swa",
"Guadeloupe": "gua",
"Kyrgyzstan": "kyr",
"Martinique": "mrt",
"Mauritania": "mau",
"Mozambique": "moz",
"San Marino": "smr",
"Seychelles": "sey",
"El Salvador": "sal",
"North Korea": "nko",
"Sierra Leone": "srl",
"Cote d'Ivoire": "civ",
"Faroe Islands": "far",
"French Polynesia": "pof",
"Papua New Guinea": "ngu",
"Dominican Republic": "dom",
"Syrian Arab Republic": "syr",
"Central African Republic": "caf",
"Democratic Republic Congo": "rdc",
"Federated States of Micronesia": "mic",
"Namibia": "nam",
"New Caledonia": "ncl",
"Nigeria": "nga",
"Netherlands": "nld",
"Norway": "nor",
"Nepal": "npl",
"New Zealand": "nzl",
"Oman": "omn",
"Pakistan": "pak",
"Panama": "pan",
"Peru": "per",
"Philippines": "phl",
"Poland": "pol",
"Puerto Rico": "pri",
"Portugal": "prt",
"Palestine": "pse",
"Qatar": "qat",
"Romania": "rou",
"Russian Federation": "rus",
"Russia": "rus",
"Rwanda": "rwa",
"Saudi Arabia": "sau",
"Sudan": "sdn",
"Senegal": "sen",
"Singapore": "sgp",
"Serbia": "srb",
"Slovakia": "svk",
"Slovenia": "svn",
"Sweden": "swe",
"Chad": "tch",
"Thailand": "tha",
"Tajikistan": "tjk",
"Timor-Leste": "tls",
"Togo": "tog",
"Trinidad and Tobago": "tto",
"Tunisia": "tun",
"Turkey": "tur",
"China-Taiwan": "twn",
"Taiwan": "twn",
"Tanzania": "tza",
"Uganda": "uga",
"Ukraine": "ukr",
"Uruguay": "ury",
"United States": "usa",
"Uzbekistan": "uzb",
"Vatican City": "vct",
"Venezuela": "ven",
"Viet Nam": "vnm",
"Vietnam": "vnm",
"Vanuatu": "vut",
"Yemen": "yem",
"South Africa": "zaf",
"Zimbabwe": "zwe"}
with open("input.txt", "r") as lis:
    with open("output.txt", "w") as lst:
        a = lis.readlines()
        for i in a:
            lst.write(countries[i[:-1]]+"\n")
